name: Artifact Demo

on: push
     
jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: create file
         run:
            mkdir temp
            echo "alpha" > temp/alpha.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: temp/
